### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by wangjiejacques** [Desgard/WeCheat#3]
WeCheatDev-bhpapsenziwlvhgwnqruwrdbspri/Build/Intermediates.noindex/WeCheatDev.build/Debug-iphonesimulator/WeCheatDevDylib.build/Script-D5AE6F0F1F87DF8E00F48E69.sh: line 2: /opt/MonkeyDev/bin/md: No such file or directory

**Comment by Desgard** [comment]
1. 需要一个砸壳的ipa放在 targetapp 目录中（我用的是 WeChat 4.5，至于怎么砸壳需要看其他的教程，传播这个不太好）
2. 需要了解 [MonkeyDev](http://monkeydev.org/)的使用方法，看文档。
